Repository ripe-tech/ripe-components-vue, pull requests merged in 2020-09, with the labels that each got.

#355 Support for breadcrumbs in container-ripe
  vue/components/ui/atoms/container/container.vue
  vue/components/ui/organisms/details/details.vue
Labels: enhancement, fast-track

#356 Added component "avatar-name"
  vue/components/ui/molecules/avatar-name/avatar-name.stories.js
  vue/components/ui/molecules/avatar-name/avatar-name.vue
  vue/components/ui/molecules/index.js
Labels: enhancement

#357 Added slot "selected" to "select" component
  vue/components/ui/molecules/select/select.vue
Labels: enhancement

#354 Details columns in "details-ripe" fill available width
  vue/components/ui/organisms/details/details.vue
Labels: enhancement

#360 Fix CSS import
  css/all.scss
  css/variables.scss
  package.json
  vue/test/webpack.config.js
Labels: bug, regression

#353 Support for more table features in filter and listing components
  vue/components/ui/molecules/filter/filter.vue
  vue/components/ui/organisms/listing/listing.vue
Labels: enhancement

#365 Buttons in footer only in details
  vue/components/ui/atoms/container/container.vue
  vue/components/ui/organisms/details/details.vue
Labels: bug, regression

#364 Fix details column width in mobile
  vue/components/ui/organisms/details/details.vue
Labels: bug, regression

#363 Added create button to "listing" component
  vue/components/ui/organisms/listing/listing.stories.js
  vue/components/ui/organisms/listing/listing.vue
Labels: enhancement

#362 Support for "router-link" in "breadcrumbs"
  vue/components/ui/atoms/breadcrumbs/breadcrumbs.vue
Labels: enhancement

#366 Add default sort prop to tables
  vue/components/ui/molecules/filter/filter.vue
  vue/components/ui/organisms/listing/listing.vue
Labels: enhancement

#350 Added ripe registry app to header
  js/apps.js
  vue/components/ui/organisms/header/assets/apps/registry.svg
  vue/components/ui/organisms/header/header.stories.js
Labels: enhancement

#367 Fix listing default sort
  vue/components/ui/organisms/listing/listing.vue
Labels: bug, regression

#368 Add maxLength to input-ripe component
  vue/components/ui/atoms/input/input.stories.js
  vue/components/ui/atoms/input/input.vue
Labels: back-port 🔮, enhancement

#369 Form Input alignment
  vue/components/ui/molecules/form-input/form-input.stories.js
  vue/components/ui/molecules/form-input/form-input.vue
Labels: back-port 🔮, enhancement

#372 Support for polyfill
  package.json
  vue/test/base.js
  vue/test/setup.js
  vue/test/webpack.config.js
Labels: enhancement

#373 #156: Fix listing search in mobile
  vue/components/ui/organisms/listing/listing.vue
Labels: bug, regression

#374 Generic form component
  vue/components/ui/atoms/container/container.vue
  vue/components/ui/molecules/form-buttons/form-buttons.stories.js
  vue/components/ui/molecules/form-buttons/form-buttons.vue
  vue/components/ui/molecules/form-buttons/index.js
  vue/components/ui/molecules/index.js
  vue/components/ui/organisms/form/form.stories.js
  vue/components/ui/organisms/form/form.vue
  vue/components/ui/organisms/index.js
Labels: enhancement

#379 Support select slots in form-ripe
  vue/components/ui/organisms/form/form.vue
Labels: enhancement

#375 #576 Animations for 404 and 500 error codes
  vue/components/ui/templates/error-part/assets/404.svg
  vue/components/ui/templates/error-part/assets/500.svg
  vue/components/ui/templates/error-part/error-part.vue
Labels: enhancement

#380 Created "avatar-name-email" component
  vue/components/ui/molecules/avatar-name-email/avatar-name-email.stories.js
  vue/components/ui/molecules/avatar-name-email/avatar-name-email.vue
  vue/components/ui/molecules/index.js
Labels: enhancement

#381 Improved select slots
  vue/components/ui/molecules/select/select.vue
  vue/components/ui/organisms/form/form.vue
Labels: enhancement
