Repository ripe-tech/ripe-components-vue, pull requests merged in 2020-10, with the labels that each got.

#384 Field types improvements
  vue/components/ui/organisms/form/form.stories.js
  vue/components/ui/organisms/form/form.vue
Labels: enhancement

#385 Added semantic classes
  js/index.js
  js/util.js
  vue/components/ui/molecules/tabs/tabs.vue
  vue/components/ui/organisms/form/form.vue
  vue/mixins/utils.js
Labels: enhancement

#387 Entity shower story and documentation
  vue/components/ui/organisms/entity-shower/entity-shower.stories.js
  vue/components/ui/organisms/entity-shower/entity-shower.vue
Labels: documentation

#388 Entity lister story and documentation
  vue/components/ui/organisms/entity-lister/entity-lister.stories.js
  vue/components/ui/organisms/entity-lister/entity-lister.vue
Labels: documentation

#391 #600: Fix storybook deprecated configs
  .storybook/addons.js
  .storybook/main.js
  .storybook/preview.js
Labels: enhancement

#389 Entity creator story and documentation
  vue/components/ui/organisms/entity-creator/entity-creator.stories.js
  vue/components/ui/organisms/entity-creator/entity-creator.vue
Labels: documentation

#390 Entity editor story and documentation
  vue/components/ui/organisms/entity-editor/entity-editor.stories.js
  vue/components/ui/organisms/entity-editor/entity-editor.vue
Labels: documentation

#395 Fix test watch script
  package.json
Labels: bug

#398 #172 Add symbol position prop to component input-symbol
  vue/components/ui/molecules/input-symbol/input-symbol.stories.js
  vue/components/ui/molecules/input-symbol/input-symbol.vue
Labels: enhancement

#400 #172 Add button icon border-radius and extra icons
  vue/assets/icons/extra/font_trimming.svg
  vue/assets/icons/extra/hat.svg
  vue/assets/icons/extra/letter_spacing.svg
  vue/assets/icons/extra/line_height.svg
  vue/assets/icons/extra/mirror_horizontal.svg
  vue/assets/icons/extra/mirror_vertical.svg
  vue/components/ui/atoms/button-icon/button-icon.stories.js
  vue/components/ui/atoms/button-icon/button-icon.vue
Labels: enhancement
