Repository ripe-tech/ripe-components-vue, pull requests merged in 2020-07, with the labels that each got.

#339 Fix table storybook
  vue/components/ui/molecules/table/table.stories.js
Labels: bug

#329 #322: Add label on empty dropdown
  vue/components/ui/atoms/dropdown/dropdown.stories.js
  vue/components/ui/atoms/dropdown/dropdown.vue
  vue/test/components/dropdown/dropdown.test.js
Labels: enhancement, fast-track, p-low, unit-testing

#342 Add semantic classes to dropdown items
  vue/components/ui/atoms/dropdown/dropdown.vue
Labels: enhancement

#343 Revert "Add semantic classes to dropdown items"
  vue/components/ui/atoms/dropdown/dropdown.vue
Labels: bug

#341 Set dropdown managed to default to false
  vue/components/ui/atoms/dropdown/dropdown.vue
Labels: bug, regression

#340 Add support for dropdown icons
  vue/components/ui/atoms/dropdown/dropdown.stories.js
  vue/components/ui/atoms/dropdown/dropdown.vue
Labels: enhancement

#345 Add data-value to dropdown
  vue/components/ui/atoms/dropdown/dropdown.vue
Labels: enhancement

#346 Reuse icon component in reaction
  vue/components/ui/atoms/reaction/reaction.vue
Labels: enhancement

#347 Backport avatar (very-large size)
  vue/components/ui/atoms/avatar/avatar.stories.js
  vue/components/ui/atoms/avatar/avatar.vue
Labels: enhancement

#348 Backport enhace upload area
  vue/components/ui/molecules/upload-area/upload-area.vue
Labels: enhancement
