Repository ripe-tech/ripe-components-vue, pull requests merged in 2020-06, with the labels that each got.

#316 Port table-expandable from ripe-white
  vue/components/ui/molecules/index.js
  vue/components/ui/molecules/table-expandable/assets/arrow-down.svg
  vue/components/ui/molecules/table-expandable/index.js
  vue/components/ui/molecules/table-expandable/table-expandable.stories.js
  vue/components/ui/molecules/table-expandable/table-expandable.vue
  vue/components/ui/molecules/table/table.vue
Labels: enhancement

#315 Add missing table CSS
  vue/components/ui/molecules/table/table.vue
Labels: bug

#317 Improve table click and hover
  vue/components/ui/molecules/table/table.vue
Labels: enhancement

#318 Fix table expandable arrow width based on variant
  vue/components/ui/molecules/table-expandable/table-expandable.vue
Labels: bug

#320 Backport tab classes
  vue/components/ui/molecules/tabs/tabs.vue
Labels: enhancement

#321 First unit test
  package.json
  vue/test/base.js
  vue/test/components/tag/tag.test.js
  vue/test/mocks/index.js
  vue/test/mocks/mixins/device.js
  vue/test/mocks/mixins/index.js
  vue/test/setup.js
  vue/test/webpack.config.js
Labels: enhancement

#297 #294 Header buttons in "container-ripe"
  vue/components/ui/atoms/container/container.stories.js
  vue/components/ui/atoms/container/container.vue
Labels: enhancement, fast-track, talk

#304 #294 Updated "listing" component after "container-ripe" changes
  vue/components/ui/organisms/listing/listing.vue
Labels: bug, enhancement, talk

#326 Port from table padding fixes
  vue/components/ui/molecules/table/table.vue
Labels: enhancement

#328 Fix unit test description
  vue/test/components/tag/tag.test.js
Labels: enhancement

#325 Add select unit tests
  vue/test/components/select/select.test.js
Labels: enhancement, fast-track

#324 Change specific items in the options dropdown of the details component
  vue/components/ui/organisms/details/details.stories.js
  vue/components/ui/organisms/details/details.vue
Labels: enhancement

#209 Checkboxes in "table-ripe" component
  vue/components/ui/molecules/filter/filter.stories.js
  vue/components/ui/molecules/filter/filter.vue
  vue/components/ui/molecules/table/table.stories.js
  vue/components/ui/molecules/table/table.vue
  vue/components/ui/organisms/listing/listing.stories.js
  vue/components/ui/organisms/listing/listing.vue
Labels: enhancement, fast-track

#330 Add logo
  README.md
  res/logo.png
  res/logo.svg
Labels: enhancement

#332 Backport select & dropdown: key buffer, global hides and shows
  vue/components/ui/atoms/dropdown/dropdown.vue
  vue/components/ui/molecules/select/select.vue
  vue/test/components/select/select.test.js
Labels: enhancement

#333 Port dropdown and select changes from ripe-white
  vue/components/ui/atoms/dropdown/dropdown.stories.js
  vue/components/ui/atoms/dropdown/dropdown.vue
  vue/components/ui/molecules/select/select.stories.js
Labels: enhancement

#334 Port tags changes
  vue/components/ui/atoms/tag/tag.vue
Labels: enhancement

#331 #327 Improve notifcation
  vue/components/ui/molecules/notification/notification.stories.js
  vue/components/ui/molecules/notification/notification.vue
Labels: enhancement
