Repository ripe-tech/ripe-components-vue, pull requests merged in 2020-11, with the labels that each got.

#397 #216 Input slider
  vue/components/ui/molecules/index.js
  vue/components/ui/molecules/input-slider/input-slider.stories.js
  vue/components/ui/molecules/input-slider/input-slider.vue
  vue/test/components/input-slider/input-slider.test.js
Labels: enhancement

#396 #216 Slider ripe
  vue/components/ui/molecules/index.js
  vue/components/ui/molecules/input-slider/input-slider.stories.js
  vue/components/ui/molecules/input-slider/input-slider.vue
  vue/components/ui/molecules/slider/slider.stories.js
  vue/components/ui/molecules/slider/slider.vue
  vue/test/components/input-slider/input-slider.test.js
  vue/test/components/slider/slider.test.js
Labels: enhancement

#394 #217 Button icon toggle
  vue/components/ui/molecules/button-icon-toggle/button-icon-toggle.stories.js
  vue/components/ui/molecules/button-icon-toggle/button-icon-toggle.vue
  vue/components/ui/molecules/index.js
  vue/test/components/button-icon-toggle/button-icon-toggle.test.js
Labels: enhancement, fast-track

#402 #172 Button-icon: using primary icon when secundary is null
  css/variables.scss
  vue/components/ui/molecules/button-icon-toggle/button-icon-toggle.vue
Labels: enhancement

#403 Improve input color
  vue/components/ui/molecules/input-color/input-color.stories.js
  vue/components/ui/molecules/input-color/input-color.vue
Labels: bug, enhancement

#404 #172 Symbol slot for input-symbol
  vue/components/ui/molecules/input-symbol/input-symbol.vue
Labels: back-port 🔮, enhancement
