Repository ripe-tech/ripe-components-vue, pull requests merged in 2021-01, with the labels that each got.

#416 Improved resize interaction after rotation
  vue/components/ui/molecules/box-resizable/box-resizable.vue
Labels: enhancement

#417 #409 Input image
  vue/assets/icons/extra/add-camera.svg
  vue/components/ui/molecules/index.js
  vue/components/ui/molecules/input-image/input-image.stories.js
  vue/components/ui/molecules/input-image/input-image.vue
  vue/components/ui/molecules/lightbox/lightbox.vue
  vue/components/ui/molecules/upload-area/upload-area.vue
  vue/test/components/input-image/input-image.js
Labels: documentation, enhancement, unit-testing

#414 #408 Steps
  vue/components/ui/molecules/index.js
  vue/components/ui/molecules/progress-bar/progress-bar.stories.js
  vue/components/ui/molecules/steps/steps.stories.js
  vue/components/ui/molecules/steps/steps.vue
  vue/test/components/steps/steps.test.js
Labels: documentation, enhancement, unit-testing

#411 #407 Bezier curve editor
  vue/components/ui/molecules/bezier-curve/bezier-curve.stories.js
  vue/components/ui/molecules/bezier-curve/bezier-curve.vue
  vue/components/ui/molecules/index.js
  vue/test/components/bezier-curve/bezier-curve.test.js
Labels: documentation, enhancement, unit-testing

#420 Fixed storybook not being in fullscreen
  .storybook/preview.js
Labels: back-port 🔮, bug

#421 Rename Zeit do Vercel
  README.md
Labels: documentation, enhancement

#422 chore: rename now to vercel
  package.json
  vercel.json
Labels: enhancement

#419 #2 Add carousel
  vue/components/ui/molecules/carousel/carousel.stories.js
  vue/components/ui/molecules/carousel/carousel.vue
  vue/components/ui/molecules/index.js
  vue/test/components/carousel/carousel.test.js
Labels: documentation, enhancement, unit-testing

#424 Blob mixin
  vue/mixins/download.js
  vue/mixins/index.js
Labels: enhancement

#426 feat: extended icons via $iconSources
  vue/components/ui/atoms/icon/icon.vue
Labels: back-port 🔮, enhancement

#427 #2 Improve carousel's cursor pointer to grabbing
  vue/components/ui/molecules/carousel/carousel.vue
Labels: enhancement

#429 feat: turn smile off by default
  vue/components/ui/atoms/rich-textarea/rich-textarea.vue
Labels: enhancement

#430 feat: sticky table header
  vue/components/ui/molecules/table/table.vue
Labels: enhancement

#432 Fix context item interation
  vue/components/ui/atoms/icon/icon.vue
Labels: bug

#434 feat: blocking send message on chat
  vue/components/ui/atoms/rich-textarea/rich-textarea.vue
  vue/components/ui/organisms/chat/chat.vue
Labels: enhancement

#435 refactor: small set of changes in chat
  vue/components/ui/organisms/chat/chat.vue
Labels: enhancement

#436 feat: chat sendMessage modify message
  vue/components/ui/organisms/chat/chat.vue
Labels: enhancement
