Repository ripe-tech/ripe-components-vue, pull requests merged in 2021-03, with the labels that each got.

#445 #165: Keyword filter logic
  js/filter.js
Labels: enhancement

#449 #165: Tooltip in listing's search
  vue/components/ui/molecules/index.js
  vue/components/ui/molecules/tooltip/tooltip.stories.js
  vue/components/ui/molecules/tooltip/tooltip.vue
  vue/components/ui/organisms/listing/listing.stories.js
  vue/components/ui/organisms/listing/listing.vue
Labels: enhancement

#378 Generic Form component - second try
  js/index.js
  js/util.js
  vue/components/ui/atoms/container/container.vue
  vue/components/ui/molecules/form-buttons/form-buttons.stories.js
  vue/components/ui/molecules/form-buttons/form-buttons.vue
  vue/components/ui/molecules/form-buttons/index.js
  vue/components/ui/molecules/index.js
  vue/components/ui/molecules/select/select.vue
  vue/components/ui/molecules/tabs/tabs.vue
  vue/components/ui/organisms/container-form/container-form.stories.js
  vue/components/ui/organisms/container-form/container-form.vue
  vue/components/ui/organisms/form/form.stories.js
  vue/components/ui/organisms/form/form.vue
  vue/components/ui/organisms/index.js
  vue/mixins/utils.js
Labels: enhancement, fast-track, risky ❕, talk

#452 Select: Mobile native toggle
  vue/components/ui/molecules/select/select.vue
Labels: bug

#453 fix: tooltip appears even with empty text
  vue/components/ui/molecules/tooltip/tooltip.vue
Labels: back-port 🔮, bug

#455 #39 Carousel swipe animation
  vue/components/ui/molecules/carousel/carousel.stories.js
  vue/components/ui/molecules/carousel/carousel.vue
Labels: enhancement

#458 feat: allow form components override
  vue/components/ui/organisms/container-form/container-form.vue
  vue/components/ui/organisms/form/form.vue
Labels: enhancement

#461 feat: pass item index to show route
  vue/components/ui/organisms/entity-list/entity-list.vue
Labels: bug

#459 fix: entity create acceptButtonProps
  vue/components/ui/organisms/entity-create/entity-create.vue
Labels: bug

#457 feat: switcher text and color props
  vue/components/ui/atoms/switcher/switcher.stories.js
  vue/components/ui/atoms/switcher/switcher.vue
Labels: enhancement

#460 fix: remove onSave call from button click
  vue/components/ui/organisms/form/form.vue
Labels: bug

#464 feat: added slot to listing's header button
  vue/components/ui/organisms/listing/listing.vue
Labels: enhancement

#465 #39 Carousel - infinite slide and double slide fix
  vue/components/ui/molecules/carousel/carousel.vue
Labels: enhancement

#463 feat: image listing components
  vue/components/ui/atoms/image-item/image-item.stories.js
  vue/components/ui/atoms/image-item/image-item.vue
  vue/components/ui/atoms/index.js
  vue/components/ui/molecules/image-list/image-list.stories.js
  vue/components/ui/molecules/image-list/image-list.vue
  vue/components/ui/molecules/index.js
Labels: enhancement, ui-ux-review 🕵️‍

#466 #39 Carousel: Using vue transition events instead of native onanimationend
  vue/components/ui/molecules/carousel/carousel.vue
Labels: enhancement

#470 fix: highlight color and highlight timing
  vue/components/ui/atoms/image-item/image-item.stories.js
  vue/components/ui/atoms/image-item/image-item.vue
  vue/components/ui/molecules/image-list/image-list.stories.js
  vue/components/ui/molecules/image-list/image-list.vue
Labels: bug
