Repository ripe-tech/ripe-components-vue, pull requests merged in 2021-06, with the labels that each got.

#506 feat: move some functions to ripe-commons
  CHANGELOG.md
  js/config.js
  js/context.js
  js/filter.js
  js/util.js
  package.json
  test/base/context.js
  vue/mixins/config.js
  vue/mixins/ripe.js
  vue/mixins/utils.js
Labels: enhancement

#507 style: fix export structure
  js/context.js
  js/filter.js
  js/util.js
Labels: enhancement

#508 fix: console error call
  vue/components/ui/molecules/alert/alert.vue
Labels: back-port 🔮, bug

#509 Update ripe-commons methods arguments
  vue/mixins/config.js
  vue/mixins/utils.js
Labels: enhancement

#511 Modal: fix title width
  vue/components/ui/molecules/modal/modal.vue
Labels: bug

#512 Resolved input-list bad v-bind
  vue/components/ui/organisms/form/form.vue
Labels: bug
