Repository ripe-tech/ripe-components-vue, pull requests merged in 2021-05, with the labels that each got.

#484 feat: all option in select-checkboxes
  CHANGELOG.md
  vue/components/ui/molecules/select-checkboxes/select-checkboxes.stories.js
  vue/components/ui/molecules/select-checkboxes/select-checkboxes.vue
Labels: enhancement, testing 👮

#485 feat: better default labels for select-checkboxes
  CHANGELOG.md
  vue/components/ui/molecules/select-checkboxes/select-checkboxes.stories.js
  vue/components/ui/molecules/select-checkboxes/select-checkboxes.vue
Labels: enhancement

#486 #60 Add image list and imagem item slots
  CHANGELOG.md
  vue/components/ui/atoms/image-item/image-item.vue
  vue/components/ui/molecules/image-list/image-list.vue
Labels: enhancement

#487 version: 0.9.1
  CHANGELOG.md
  package.json
Labels: enhancement

#488 feat: use latest vue-test-utils version
  package.json
Labels: enhancement

#489 Image list: Option to use id as a key
  CHANGELOG.md
  vue/components/ui/molecules/image-list/image-list.vue
Labels: enhancement

#490 refactor: button-icon-dropdown tweaks
  vue/components/ui/molecules/button-icon-dropdown/button-icon-dropdown.vue
Labels: enhancement

#492 Accepting numbers in value prop
  CHANGELOG.md
  vue/components/ui/atoms/radio/radio.vue
  vue/components/ui/molecules/radio-group/radio-group.vue
  vue/components/ui/molecules/select/select.vue
Labels: enhancement

#493 fix: new storybook 'stories' format to fix watch getting constantly triggering build
  .storybook/main.js
Labels: bug

#494 refactor: input list add button position
  vue/components/ui/organisms/input-list/input-list.stories.js
  vue/components/ui/organisms/input-list/input-list.vue
Labels: enhancement

#496 feat: inline select prop
  CHANGELOG.md
  vue/components/ui/molecules/select/select.stories.js
  vue/components/ui/molecules/select/select.vue
Labels: enhancement

#497 feat: add container overflow prop
  CHANGELOG.md
  vue/components/ui/atoms/container/container.stories.js
  vue/components/ui/atoms/container/container.vue
Labels: enhancement

#498 feat: inline container and listing
  CHANGELOG.md
  vue/components/ui/atoms/container/container.stories.js
  vue/components/ui/atoms/container/container.vue
  vue/components/ui/organisms/listing/listing.stories.js
Labels: enhancement

#500 feat: container header buttons type
  CHANGELOG.md
  vue/components/ui/atoms/container/container.stories.js
  vue/components/ui/atoms/container/container.vue
Labels: enhancement

#502 Add typeless value support
  CHANGELOG.md
  vue/components/ui/atoms/radio/radio.vue
  vue/components/ui/molecules/radio-group/radio-group.vue
  vue/components/ui/molecules/select/select.vue
Labels: back-port 🔮, enhancement

#499 fix: fix upload area component
  CHANGELOG.md
  vue/components/ui/molecules/upload-area/upload-area.vue
Labels: enhancement, talk
