Repository ripe-tech/ripe-components-vue, pull requests merged in 2021-04, with the labels that each got.

#472 fix: image-item highlight if true when mounted
  vue/components/ui/atoms/image-item/image-item.vue
Labels: bug

#474 fix: search bar uses all width in mobile
  package.json
  vue/components/ui/organisms/listing/listing.vue
Labels: bug, regression

#475 feat: fallback support for hasFeature
  js/config.js
Labels: back-port 🔮, enhancement

#477 feat: input list font size
  vue/components/ui/organisms/input-list/input-list.vue
Labels: bug

#476 feat: form toValue and fromValue
  vue/components/ui/organisms/form/form.vue
Labels: enhancement, risky ❕, talk

#478 fix: lock vue-test-utils version
  package.json
Labels: bug

#480 feat: add list input to form
  vue/components/ui/organisms/form/form.vue
Labels: enhancement

#481 Fix storybook structure
  vue/components/ui/organisms/entity-show/entity-show.stories.js
Labels: enhancement

#482 version: 0.8.34
  package.json
Labels: enhancement

#483 Image Item: fix image fit
  vue/components/ui/atoms/image-item/image-item.vue
  vue/components/ui/molecules/image-list/image-list.vue
Labels: enhancement
