Repository ripe-tech/ripe-components-vue, pull requests merged in 2022-06, with the labels that each got.

#598 #305 Fix `code-editor` `value` emit event
  CHANGELOG.md
  vue/components/ui/molecules/code-editor/code-editor.vue
Labels: bug

#600 #288 sortedItems Event
  CHANGELOG.md
  vue/components/ui/molecules/table/table.vue
Labels: enhancement

#599 #288 button-dropdown disabled prop
  CHANGELOG.md
  vue/components/ui/molecules/button-dropdown/button-dropdown.stories.js
  vue/components/ui/molecules/button-dropdown/button-dropdown.vue
Labels: enhancement, back-port 🔮

#591 Add debounce delay to `input-symbol` component
  CHANGELOG.md
  vue/components/ui/molecules/input-symbol/input-symbol.vue
Labels: enhancement

#602 #302 Revert - fix spreadsheet icon
  CHANGELOG.md
  vue/assets/icons/spreadsheet.svg
Labels: enhancement

#603 version: 0.23.1
  CHANGELOG.md
  package.json
Labels: enhancement, release 🎉
