Repository ripe-tech/ripe-components-vue, pull requests merged in 2022-05, with the labels that each got.

#587 Input: `debounceTime` prop
  CHANGELOG.md
  vue/components/ui/atoms/input/input.stories.js
  vue/components/ui/atoms/input/input.vue
Labels: enhancement

#589 feat: global hide prop in button icon dropdown
  CHANGELOG.md
  vue/components/ui/atoms/dropdown/dropdown.vue
  vue/components/ui/molecules/button-icon-dropdown/button-icon-dropdown.vue
Labels: enhancement

#582 #571 - Add Avatar List Component
  CHANGELOG.md
  vue/components/ui/molecules/avatar-list/avatar-list.stories.js
  vue/components/ui/molecules/avatar-list/avatar-list.vue
  vue/components/ui/molecules/index.js
Labels: enhancement

#588 Add slots to `input-symbol` component
  CHANGELOG.md
  vue/components/ui/molecules/input-symbol/input-symbol.stories.js
  vue/components/ui/molecules/input-symbol/input-symbol.vue
Labels: enhancement

#590 Fix Spreadsheet Icon Stroke Width
  CHANGELOG.md
  vue/assets/icons/spreadsheet.svg
Labels: bug

#594 Support node `16` , `17` and `18`
  .github/workflows/main.yml
  CHANGELOG.md
Labels: enhancement

#596 fix: eslint dependencies problems
  CHANGELOG.md
  package.json
  vue/components/ui/organisms/table-menu/table-menu.vue
Labels: bug, back-port 🔮

#592 `header-ripe` improvements - Remove hardcoded announcements
  CHANGELOG.md
  vue/components/ui/organisms/header/header.vue
Labels: enhancement
