Repository ripe-tech/ripe-components-vue, pull requests merged in 2022-03, with the labels that each got.

#556 version: 0.19.0
  CHANGELOG.md
  package.json
Labels: release 🎉

#555 feat: disabled items for dropdown component
  CHANGELOG.md
  vue/components/ui/atoms/dropdown/dropdown.stories.js
  vue/components/ui/atoms/dropdown/dropdown.vue
Labels: enhancement, back-port 🔮

#559 Improved feature set for tooltips
  vue/components/ui/molecules/tooltip/tooltip.stories.js
  vue/components/ui/molecules/tooltip/tooltip.vue
Labels: enhancement

#560 #302 - Remove Stroke for Spreadsheet Icon
  CHANGELOG.md
  vue/assets/icons/spreadsheet.svg
Labels: enhancement, no-changelog

#568 #256 Support `section-expandable` new `expanded` prop
  CHANGELOG.md
  vue/components/ui/molecules/section-expandable/section-expandable.stories.js
  vue/components/ui/molecules/section-expandable/section-expandable.vue
Labels: enhancement
