Repository ripe-tech/ripe-components-vue, pull requests merged in 2022-04, with the labels that each got.

#567 #257 `code-editor` component
  CHANGELOG.md
  package.json
  vue/components/ui/molecules/code-editor/code-editor.stories.js
  vue/components/ui/molecules/code-editor/code-editor.vue
  vue/components/ui/molecules/index.js
Labels: enhancement

#569 #265 Fix `section-expandable` not handling dynamic content height
  CHANGELOG.md
  vue/components/ui/molecules/section-expandable/section-expandable.vue
Labels: bug

#562 fix: Immediately watch ´valueData´ in select component
  CHANGELOG.md
  vue/components/ui/molecules/select/select.vue
  vue/test/components/select/select.test.js
Labels: bug, unit-testing

#570 feat: disabled button icon dropdown
  CHANGELOG.md
  vue/components/ui/molecules/button-icon-dropdown/button-icon-dropdown.stories.js
  vue/components/ui/molecules/button-icon-dropdown/button-icon-dropdown.vue
Labels: enhancement

#572 Version: 0.21.0
  CHANGELOG.md
  package.json
Labels: release 🎉

#573 #316 Support custom panel in `header-ripe`
  CHANGELOG.md
  vue/components/ui/atoms/dropdown/dropdown.vue
  vue/components/ui/organisms/header/header.stories.js
  vue/components/ui/organisms/header/header.vue
Labels: enhancement

#577 #316 Add `entry` component
  CHANGELOG.md
  vue/components/ui/atoms/entry/entry.stories.js
  vue/components/ui/atoms/entry/entry.vue
  vue/components/ui/atoms/index.js
Labels: enhancement

#578 #316 Fix `header-ripe` by reverting some refactor changes
  CHANGELOG.md
  vue/components/ui/organisms/header/header.vue
Labels: bug

#581 #580 Closing the file browser dialog removes the previous selected file in upload components #580
  CHANGELOG.md
  vue/mixins/upload.js
Labels: bug

#579 #270 `select-checkboxes` search bar
  CHANGELOG.md
  vue/components/ui/atoms/dropdown/dropdown.vue
  vue/components/ui/molecules/select-checkboxes/select-checkboxes.stories.js
  vue/components/ui/molecules/select-checkboxes/select-checkboxes.vue
  vue/components/ui/molecules/select/select.vue
Labels: enhancement

#583 #270 Support webpack@4 `raw-loader` logic for icons provided by external sources
  CHANGELOG.md
  vue/components/ui/atoms/icon/icon.vue
Labels: bug

#584 #270 `iconPosition` prop for `button-color`
  CHANGELOG.md
  vue/components/ui/atoms/button-color/button-color.stories.js
  vue/components/ui/atoms/button-color/button-color.vue
Labels: enhancement

#585 Version: 0.22.0
  CHANGELOG.md
  package.json
Labels: release 🎉

#575 feat: add input-file component
  CHANGELOG.md
  vue/components/ui/molecules/index.js
  vue/components/ui/molecules/input-file/input-file.stories.js
  vue/components/ui/molecules/input-file/input-file.vue
Labels: enhancement
