Repository ripe-tech/ripe-components-vue, pull requests merged in 2022-02, with the labels that each got.

#547 #296 Add `textColor` prop to `tag` component
  CHANGELOG.md
  vue/components/ui/atoms/tag/tag.vue
Labels: enhancement

#548 #296 Add `backgroundColor` prop to `progress-bar` component
  CHANGELOG.md
  vue/components/ui/molecules/progress-bar/progress-bar.vue
Labels: enhancement

#550 feat: use inline raw-loader similar logic with new webpack loaders
  .storybook/webpack.config.js
  CHANGELOG.md
  vue/components/ui/atoms/attachments/attachments.stories.js
  vue/components/ui/atoms/icon/icon.vue
  vue/components/ui/molecules/carousel/carousel.stories.js
  vue/components/ui/molecules/chat-message/chat-message.stories.js
  vue/components/ui/molecules/footer/footer.vue
  vue/components/ui/organisms/chat/chat.stories.js
  vue/mixins/device.js
  vue/test/components/select-checkboxes/select-checkboxes.test.js
  webpack.config.js
Labels: enhancement

#551 fix: removed href from dropdown story
  CHANGELOG.md
  vue/components/ui/atoms/dropdown/dropdown.stories.js
  webpack.config.js
Labels: bug, back-port 🔮

#552 fix: apply correctly the border radius in `image-item`
  CHANGELOG.md
  vue/components/ui/atoms/image-item/image-item.vue
Labels: bug
