Repository ripe-tech/ripe-components-vue, pull requests merged in 2022-10, with the labels that each got.

#610 fix: proper icon context paths
  CHANGELOG.md
  vue/components/ui/atoms/icon/icon.vue
Labels: bug, hacktoberfest-accepted

#611 version: 0.23.2 :rainbow:
  CHANGELOG.md
  package.json
Labels: release 🎉, hacktoberfest-accepted

#613 #612 `upload-area` component not clearing data
  CHANGELOG.md
  vue/components/ui/molecules/button-upload/button-upload.vue
  vue/mixins/upload.js
Labels: bug
