Repository ripe-tech/ripe-components-vue, pull requests merged in 2022-12, with the labels that each got.

#621 fix: view on white button
  CHANGELOG.md
  vue/components/ui/atoms/button-color/button-color.vue
Labels: bug, p-low

#622 #240 Filter orders
  CHANGELOG.md
  vue/components/ui/organisms/listing/listing.vue
Labels: enhancement

#623 version: 0.23.5
  CHANGELOG.md
  package.json
Labels: release 🎉
