Repository ripe-tech/ripe-components-vue, pull requests merged in 2022-11, with the labels that each got.

#614 feat: add reacticity to `emptySlots()` computed property in `molecules/upload-area.vue`
  CHANGELOG.md
  vue/components/ui/molecules/input-file/input-file.vue
  vue/components/ui/molecules/upload-area/upload-area.vue
  vue/mixins/upload.js
Labels: enhancement

#615 fix: fix test-utils version to 1.3.0
  CHANGELOG.md
  package.json
Labels: bug

#616 version: `0.23.3`
  CHANGELOG.md
  package.json
Labels: release 🎉

#617 button-color improvements
  CHANGELOG.md
  vue/components/ui/atoms/button-color/button-color.stories.js
  vue/components/ui/atoms/button-color/button-color.vue
Labels: enhancement

#618 fix: `noFileSelected()` computed property to handle `null` values and consequently adapt `emptySlots()` computed property
  CHANGELOG.md
  package.json
  vue/components/ui/molecules/upload-area/upload-area.vue
  vue/mixins/upload.js
Labels: bug, p-medium

#619 Fix vue-loader config and bump `stylelint-config-hive`
  css/all.scss
  css/page.scss
  package.json
  vue/components/ui/atoms/button-icon/button-icon.vue
  vue/components/ui/atoms/input/input.vue
  vue/components/ui/atoms/radio/radio.vue
  vue/components/ui/atoms/textarea/textarea.vue
  vue/test/webpack.config.js
Labels: back-port 🔮

#620 version: `0.23.4`
  CHANGELOG.md
  package.json
Labels: release 🎉
